config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                    Controller#Action
#               root GET    /                                              static_pages#home
#             filter POST   /filter(.:format)                              static_pages#filter
#          mapchange POST   /mapchange(.:format)                           static_pages#mapchange
#        crimefilter POST   /crimefilter(.:format)                         schools#crimefilter
#              about GET    /about(.:format)                               static_pages#about
#            contact GET    /contact(.:format)                             static_pages#contact
#             signup GET    /signup(.:format)                              users#new
#                    POST   /signup(.:format)                              users#create
#       sessions_new GET    /sessions/new(.:format)                        sessions#new
#              login GET    /login(.:format)                               sessions#new
#                    POST   /login(.:format)                               sessions#create
#             logout DELETE /logout(.:format)                              sessions#destroy
#     school_reviews GET    /schools/:school_id/reviews(.:format)          reviews#index
#                    POST   /schools/:school_id/reviews(.:format)          reviews#create
#  new_school_review GET    /schools/:school_id/reviews/new(.:format)      reviews#new
# edit_school_review GET    /schools/:school_id/reviews/:id/edit(.:format) reviews#edit
#      school_review GET    /schools/:school_id/reviews/:id(.:format)      reviews#show
#                    PATCH  /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    PUT    /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    DELETE /schools/:school_id/reviews/:id(.:format)      reviews#destroy
#    favorite_school POST   /schools/:id/favorite(.:format)                schools#favorite
#            schools GET    /schools(.:format)                             schools#index
#             school GET    /schools/:id(.:format)                         schools#show
#            reviews GET    /reviews(.:format)                             reviews#index
#                    POST   /reviews(.:format)                             reviews#create
#         new_review GET    /reviews/new(.:format)                         reviews#new
#        edit_review GET    /reviews/:id/edit(.:format)                    reviews#edit
#             review GET    /reviews/:id(.:format)                         reviews#show
#                    PATCH  /reviews/:id(.:format)                         reviews#update
#                    PUT    /reviews/:id(.:format)                         reviews#update
#                    DELETE /reviews/:id(.:format)                         reviews#destroy
#              users GET    /users(.:format)                               users#index
#                    POST   /users(.:format)                               users#create
#           new_user GET    /users/new(.:format)                           users#new
#          edit_user GET    /users/:id/edit(.:format)                      users#edit
#               user GET    /users/:id(.:format)                           users#show
#                    PATCH  /users/:id(.:format)                           users#update
#                    PUT    /users/:id(.:format)                           users#update
#                    DELETE /users/:id(.:format)                           users#destroy
#

Rails.application.routes.draw do
  get '/', to: 'static_pages#home', :as => 'root'
  post 'filter', to: 'static_pages#filter'
  post 'mapchange', to: 'static_pages#mapchange'
  post 'crimefilter', to: 'schools#crimefilter'
  post 'submit', to: 'schools#submit'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'sessions/new'
  get 'login',   to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  resources :schools, only: [:index, :show] do
    resources :reviews
    member do
      post 'favorite'
    end
  end
  resources :reviews
  resources :users, except: :index
   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @schools = School.all
    respond_to do |format|
        format.html
        format.js
    end
  end
  
  def about
  end
  
  def filter
    @schools = []
    some = 0;
    params["chkbox_state"].each_pair { |k, v|
      if v == "1" then
        some = 1
        @schools += School.all.select { |x| x.grade_level.downcase.include? k if x.grade_level}
      end
    }
    
    @schools = @schools.uniq
    
    @schools = School.all if some == 0

    respond_to do |format|
        format.js
    end
  end
  
  def mapchange
    @schools = []
    some = 0
    params["chkbox_state"].each_pair { |k, v|
      if v == "1" then
        some = 1
        @schools += School.all.select { |x| x.grade_level.downcase.include? k if x.grade_level}
      end
    }
    
    @schools = @schools.uniq
    
    @schools = School.all if some == 0
    
    @schools = @schools.select { |s|
      s["latitude"].to_f < params["bounds"]["lat_max"].to_f && s["latitude"].to_f > params["bounds"]["lat_min"].to_f && s["longitude"].to_f < params["bounds"]["lng_max"].to_f && s["longitude"].to_f > params["bounds"]["lng_min"].to_f
    }

    respond_to do |format|
        format.js
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_filter.html.erb
<div class="filters">
<%= form_for(:static_pages, url: filter_path, remote: true) do |f| %>
    <div class="checkbox-inline">
        <%= f.check_box :pre, onchange: "form_submit();"%>
        <%= f.label "Preschool" %>
    </div>
    <div class="checkbox-inline">
        <%= f.check_box :elem, onchange: "form_submit();" %>
        <%= f.label "Elementary"%>
    </div>
    <div class="checkbox-inline">
        <%= f.check_box :mid, onchange: "form_submit();" %>
        <%= f.label "Middle"%>
    </div>
    <div class="checkbox-inline">
        <%= f.check_box :high, onchange: "form_submit();" %>
        <%= f.label "High"%>
    </div>
<% end %>
</div>
<script>
    function form_submit() {
        var bounds = map.getBounds();
        var ne = bounds.getNorthEast(); // LatLng of the north-east corner
        var sw = bounds.getSouthWest(); // LatLng of the south-west corner
        var center = map.getCenter();
        var zoomlevel = map.getZoom();
        var pre = "0", elem = "0", mid = "0", high = "0";
        if(document.getElementById('static_pages_pre').checked)
            pre = "1";
        if(document.getElementById('static_pages_elem').checked)
            elem = "1";
        if(document.getElementById('static_pages_mid').checked)
            mid = "1";
        if(document.getElementById('static_pages_high').checked)
            high = "1";
        $.ajax({
            type: "POST",
            url: '/filter',
            data: {chkbox_state: {'pre': pre, 'elem': elem, 'mid': mid, 'high': high}, bounds: {lat_max: ne.lat(), lat_min: sw.lat(), lng_min: sw.lng(), lng_max: ne.lng(), center_lat: center.lat(), center_lng: center.lng(), zoom_level: zoomlevel}}
        });
    }
</script>

app/views/static_pages/_list.html.erb
<% @schools.each do |s| %>
  <% sid = s["id"] %>
    <div class="panel panel-default list-elem">
      <div class="panel-heading">
        <%= link_to s["name"], school_path(:id => sid), :remote => true %>
      </div>
      <div class="panel-body">
        <p>
          <%= s["address"] %>
        </p>
        <p>
          <%= s["grade_level"] %>
        </p>
      </div>
    </div>
  <% end %>

app/views/static_pages/_map.html.erb
<div id="map"></div>
<script type="text/javascript"> 
    (function initMap() {
        document.getElementById('map').style.height = String(document.getElementsByClassName('container fill')[0].offsetHeight) + "px";
        
        var centerPos = {lat: 40.0048632, lng: -75.1880722};
        var zoom_level = 12;
        
        <% if params.key? :bounds then %>
          <% if params[:bounds].key? :center_lat then %>
            centerPos = {lat: <%= params["bounds"]["center_lat"].to_f %>, lng: <%= params["bounds"]["center_lng"].to_f %>};
            zoom_level = <%= params["bounds"]["zoom_level"].to_i %>;
          <% end %>
        <% end %>
        
        map = new google.maps.Map(document.getElementById('map'), {
              zoom: zoom_level,
              center: centerPos
        });
        
        var gmInput = document.getElementById('map-input');
        var searchBox = new google.maps.places.SearchBox(gmInput);
        
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });
        
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();
          if (places.length == 0) {
            return;
          }
          var pl = places[0];
          var pl_coords = pl.geometry.location;
          
          var bounds = map.getBounds();
          var ne = bounds.getNorthEast(); // LatLng of the north-east corner
          var sw = bounds.getSouthWest(); // LatLng of the south-west corner
          var zoomlevel = 17;
          var pre = "0", elem = "0", mid = "0", high = "0";
          if(document.getElementById('static_pages_pre').checked)
            pre = "1";
          if(document.getElementById('static_pages_elem').checked)
            elem = "1";
          if(document.getElementById('static_pages_mid').checked)
            mid = "1";
          if(document.getElementById('static_pages_high').checked)
            high = "1";
          $.ajax({
            type: "POST",
            url: '/filter',
            data: {chkbox_state: {'pre': pre, 'elem': elem, 'mid': mid, 'high': high}, bounds: {lat_max: ne.lat(), lat_min: sw.lat(), lng_min: sw.lng(), lng_max: ne.lng(), center_lat: pl_coords.lat(), center_lng: pl_coords.lng(), zoom_level: zoomlevel}}
          });
        });
       
        google.maps.event.addListener(map, 'idle', function(ev){
          var bounds = map.getBounds();
          var ne = bounds.getNorthEast(); // LatLng of the north-east corner
          var sw = bounds.getSouthWest(); // LatLng of the south-west corner
          var center = map.getCenter();
          var zoomlevel = map.getZoom();
          var pre = "0", elem = "0", mid = "0", high = "0";
          if(document.getElementById('static_pages_pre').checked)
            pre = "1";
          if(document.getElementById('static_pages_elem').checked)
            elem = "1";
          if(document.getElementById('static_pages_mid').checked)
            mid = "1";
          if(document.getElementById('static_pages_high').checked)
            high = "1";
          $.ajax({
            type: "POST",
            url: '/mapchange',
            data: {chkbox_state: {'pre': pre, 'elem': elem, 'mid': mid, 'high': high}, bounds: {lat_max: ne.lat(), lat_min: sw.lat(), lng_min: sw.lng(), lng_max: ne.lng(), center_lat: center.lat(), center_lng: center.lng(), zoom_level: zoomlevel}}
          });
        });
        var infowindow = new google.maps.InfoWindow();
        <% schools.each do |s| %>
          var lat = <%= s["latitude"].to_f %>;
          var lng = <%= s["longitude"].to_f %>;
          var pos = {lat: lat, lng: lng};
          <% school_name = s["name"].gsub(/\r\n/,"") %>
          var contentString = <%= raw("'"+(link_to school_name, school_path(:id => s["id"]), :remote => true)+"'") %>;
          var marker = new google.maps.Marker({
          position: pos,
          map: map,
          <% if (Rails.env != "production") then %>
          title: "<%= school_name %>",
          optimized: false
          <% end %>
          });
          marker.info = new google.maps.InfoWindow({
            content: contentString
          });
          marker.addListener('mouseover', function() {
            infowindow.close();
            infowindow = this.info;
            infowindow.open(map, this);
          });
        <% end %>
    })();
</script>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
  <p style="text-align: center">
    The SchoolSafe application evaluates the safety of schools in the Philadelphia area.
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p style="text-align:center">
  Contact the SchoolSafe team at
</p>

app/views/static_pages/filter.js.erb
$("#list_elems").html("<%= escape_javascript(render partial: 'list', locals: { schools: @schools }) %> ");
$("#map_part").html("<%= escape_javascript(render partial: 'map', locals: { schools: @schools }) %> ");

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div id="map_part">
  <%= render partial: 'map', locals: { schools: @schools } %>
</div>

<div id="list">
  <%= render partial: 'filter' %>
  <div id="list_elems">
    <%= render partial: 'list', locals: { schools: @schools } %>
  </div>
</div>

app/views/static_pages/login.html.erb
<% provide(:title, "Log in") %>
<h1 style="padding-top: 5%">Log in</h1>
<p>Log in to your account to bookmark schools and post comments.</p>
<p>Don't have an account? <%= link_to "Sign up now!", signup_path %></p>

app/views/static_pages/mapchange.js.erb
$("#list_elems").html("<%= escape_javascript(render partial: 'list', locals: { schools: @schools }) %>");