config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                    Controller#Action
#               root GET    /                                              static_pages#home
#             filter POST   /filter(.:format)                              static_pages#filter
#          mapchange POST   /mapchange(.:format)                           static_pages#mapchange
#        crimefilter POST   /crimefilter(.:format)                         schools#crimefilter
#              about GET    /about(.:format)                               static_pages#about
#            contact GET    /contact(.:format)                             static_pages#contact
#             signup GET    /signup(.:format)                              users#new
#                    POST   /signup(.:format)                              users#create
#       sessions_new GET    /sessions/new(.:format)                        sessions#new
#              login GET    /login(.:format)                               sessions#new
#                    POST   /login(.:format)                               sessions#create
#             logout DELETE /logout(.:format)                              sessions#destroy
#     school_reviews GET    /schools/:school_id/reviews(.:format)          reviews#index
#                    POST   /schools/:school_id/reviews(.:format)          reviews#create
#  new_school_review GET    /schools/:school_id/reviews/new(.:format)      reviews#new
# edit_school_review GET    /schools/:school_id/reviews/:id/edit(.:format) reviews#edit
#      school_review GET    /schools/:school_id/reviews/:id(.:format)      reviews#show
#                    PATCH  /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    PUT    /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    DELETE /schools/:school_id/reviews/:id(.:format)      reviews#destroy
#    favorite_school POST   /schools/:id/favorite(.:format)                schools#favorite
#            schools GET    /schools(.:format)                             schools#index
#             school GET    /schools/:id(.:format)                         schools#show
#            reviews GET    /reviews(.:format)                             reviews#index
#                    POST   /reviews(.:format)                             reviews#create
#         new_review GET    /reviews/new(.:format)                         reviews#new
#        edit_review GET    /reviews/:id/edit(.:format)                    reviews#edit
#             review GET    /reviews/:id(.:format)                         reviews#show
#                    PATCH  /reviews/:id(.:format)                         reviews#update
#                    PUT    /reviews/:id(.:format)                         reviews#update
#                    DELETE /reviews/:id(.:format)                         reviews#destroy
#              users GET    /users(.:format)                               users#index
#                    POST   /users(.:format)                               users#create
#           new_user GET    /users/new(.:format)                           users#new
#          edit_user GET    /users/:id/edit(.:format)                      users#edit
#               user GET    /users/:id(.:format)                           users#show
#                    PATCH  /users/:id(.:format)                           users#update
#                    PUT    /users/:id(.:format)                           users#update
#                    DELETE /users/:id(.:format)                           users#destroy
#

Rails.application.routes.draw do
  get '/', to: 'static_pages#home', :as => 'root'
  post 'filter', to: 'static_pages#filter'
  post 'mapchange', to: 'static_pages#mapchange'
  post 'crimefilter', to: 'schools#crimefilter'
  post 'submit', to: 'schools#submit'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'sessions/new'
  get 'login',   to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  resources :schools, only: [:index, :show] do
    resources :reviews
    member do
      post 'favorite'
    end
  end
  resources :reviews
  resources :users, except: :index
   
end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id          :integer          not null, primary key
#  name        :string
#  address     :string
#  zipcode     :string
#  grade_level :string
#  school_type :string
#  latitude    :string
#  longitude   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class School < ActiveRecord::Base
    has_many :reviews
    
    belongs_to :user
    has_many :favorite_schools
    has_many :favorited_by, through: :favorite_schools, source: :user 
    
    validates :name, presence: true
    validates :address, presence: true
    validates :zipcode, presence: true
    validates :grade_level, presence: true
    validates :school_type, presence: true
    validates :latitude, presence: true
    validates :longitude, presence: true
    
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:new, :submit]
  
  @@client = SODA::Client.new({:domain => "data.phila.gov", :app_token => "A2UU0wuMdd6NOSuwVvjSu5i3u"})
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
    lat = @school.latitude
    long = @school.longitude
    @crimes = @@client.get("sspu-uyfa", {"$where" => "within_circle(shape, #{lat}, #{long}, 300) AND ucr_general in ('100', '200', '400', '1400', '1600', '1700', '1800', '1900', '2000', '2400', '2500') AND dispatch_date_time between '#{Time.now.year-3}-#{Time.now.month}-#{Time.now.day}T00:00:00' and '#{Time.now.year}-#{Time.now.month}-#{Time.now.day}T00:00:00'"})
    
    @score = @crimes.inject(0) { |sum, c|
      if ["100", "200"].include? c["ucr_general"] then
        sum + 5 
      elsif ["1700", "2000"].include? c["ucr_general"] then
        sum + 4
      elsif ["400", "1600", "1800"].include? c["ucr_general"] then
        sum + 3
      elsif ["1400", "1900"].include? c["ucr_general"] then
        sum + 2
      elsif ["2400", "2500"].include? c["ucr_general"] then
        sum + 1
      end
    }
    
    @score = @score.to_f / @crimes.length
    @score = 5 - @score
    @score = @score.to_i
    
    respond_to do |format|
        format.js
        format.html do
          redirect_to '/'
        end
    end
  end
  
  def submit
    review_params = params[:review].permit(:school_id, :title, :rating, :comment)
    @review = current_user.reviews.build(review_params)
    @school = School.find(params[:review][:school_id])
    
    lat = @school.latitude
    long = @school.longitude
    @crimes = @@client.get("sspu-uyfa", {"$where" => "within_circle(shape, #{lat}, #{long}, 300) AND ucr_general in ('100', '200', '400', '1400', '1600', '1700', '1800', '1900', '2000', '2400', '2500') AND dispatch_date_time between '#{Time.now.year-3}-#{Time.now.month}-#{Time.now.day}T00:00:00' and '#{Time.now.year}-#{Time.now.month}-#{Time.now.day}T00:00:00'"})
    
    @score = @crimes.inject(0) { |sum, c|
      if ["100", "200"].include? c["ucr_general"] then
        sum + 5 
      elsif ["1700", "2000"].include? c["ucr_general"] then
        sum + 4
      elsif ["400", "1600", "1800"].include? c["ucr_general"] then
        sum + 3
      elsif ["1400", "1900"].include? c["ucr_general"] then
        sum + 2
      elsif ["2400", "2500"].include? c["ucr_general"] then
        sum + 1
      end
    }
    
    if @review.save then
      flash[:notice] = 'Review was successfully created.'
      respond_to do |format|
        format.js
      end
    else
      flash[:notice] = 'Errors prohibited this review from being saved.'
      respond_to do |format|
        format.js
      end
    end
  end
  
  def crimefilter
    @school = School.find(params[:id])
    lat = School.find(params[:id]).latitude
    long = School.find(params[:id]).longitude
    classes = params[:classes].join("', '")
    classes = "('" + classes
    classes += "')"
    
    @crimes = @@client.get("sspu-uyfa", {"$where" => "within_circle(shape, #{lat}, #{long}, #{params[:radius_val].to_i*100}) AND dispatch_date_time between '#{Time.now.year-params[:range_val].to_i}-#{Time.now.month}-#{Time.now.day}T00:00:00' and '#{Time.now.year}-#{Time.now.month}-#{Time.now.day}T00:00:00' AND ucr_general in #{classes}"})
    
    @score = @crimes.inject(0) { |sum, c|
      if ["100", "200"].include? c["ucr_general"] then
        sum + 5 
      elsif ["1700", "2000"].include? c["ucr_general"] then
        sum + 4
      elsif ["400", "1600", "1800"].include? c["ucr_general"] then
        sum + 3
      elsif ["1400", "1900"].include? c["ucr_general"] then
        sum + 2
      elsif ["2400", "2500"].include? c["ucr_general"] then
        sum + 1
      end
    }
    
    if @crimes.length == 0 then
      @score = 0
    else
      @score = @score.to_f / @crimes.length
    end
    
    @score = 5 - @score
    @score = @score.to_i

    respond_to do |format|
        format.js
    end
  end
  
  # Add and remove favorite recipes
  # for current_user
  def favorite
    type = params[:type]
    @school = School.find(params[:id])
    if type == "favorite"
      current_user.favorites << @school
      redirect_to @school, notice: "You bookmarked #{@school.name}"

    elsif type == "unfavorite"
      current_user.favorites.delete(@school)
      redirect_to @school, notice: "Removed bookmark for #{@school.name}"

    else
      # Type missing, nothing happens
      redirect_to @school, notice: "Nothing happened."
    end
  end
  
  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.fetch(:school, {})
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
    def favorite? (school)
        current_user.favorites.include? school
    end
end

app/views/schools/_crimes.html.erb
<% if crimes.length == 0 then %>
  <div class="alert alert-danger" style="margin-top: 10%; text-align: center">
      No crimes found!
  </div>
<% else %>
  <h3 style="margin-bottom: 5%">List of Crimes: </h3>
  <ul class="list-group" style="margin-bottom: 10%">
  <% crimes.each do |r| %>
    <li class="list-group-item">
      <%= r["dispatch_date"] %>  | 
      <%= r["text_general_code"] %>
    </li>
  <% end %>
  </ul>
<% end %>

app/views/schools/_crimesfilter.html.erb
<div id="crime-filters">
    <h2>Select Crime Type(s):</h2>
    <form>
        <select name="crime_types" multiple onchange="filter_map();">
          <option value="100">Homicide</option>
          <option value="200">Rape</option>
          <option value="400">Aggravated Assault</option>
          <option value="1400">Vandalism</option>
          <option value="1600">Prostitution</option>
          <option value="1700">Other Sex Offences</option>
          <option value="1800">Drug Violations</option>
          <option value="1900">Gambling Violations</option>
          <option value="2000">Offences against Family and Children</option>
          <option value="2400">Disorderly Conduct</option>
          <option value="2500">Vagrancy/Loitering</option>
        </select>
    </form>
    <h2>Select Years of Crime Records:</h2>
    <div id="rangeDiv">
        <input type="range" id="rangeInput" name="rangeInput" step="1" min="1"
max="5" defaultValue="3" onchange="filter_map();">
        <label id="rangeText">
    </div>
    <h2>Select Radius of Crime Records (in m):</h2>
    <div id="radiusDiv">
        <input type="range" id="radiusInput" name="radiusInput" step="1" min="1"
max="5" defaultValue="3" onchange="filter_map();">
        <label id="radiusText">
    </div>
    
</div>

<script>

    function filter_map() {
        var classes = [];
        var some = 0;
        for(var i = 0; i < document.getElementsByName('crime_types')[0].options.length; i += 1) {
            if(document.getElementsByName('crime_types')[0].options[i].selected) {
                some = 1;
                classes.push(document.getElementsByName('crime_types')[0].options[i].value);
            }
        }
        if(some == 0) {
            for(var i = 0; i < document.getElementsByName('crime_types')[0].options.length; i += 1) {
                classes.push(document.getElementsByName('crime_types')[0].options[i].value);
            }
        }
        $.ajax({
            type: "POST",
            url: '/crimefilter',
            data: {'id': <%= id %>, 'radius_val': document.getElementById('radiusInput').value, 'range_val': document.getElementById('rangeInput').value, 'classes': classes}
        });
    }
    
    
    var rangeValues = {
        "1": "Past 1 year",
        "2": "Past 2 years",
        "3": "Past 3 years",
        "4": "Past 4 years",
        "5": "Past 5 years"
    };
    
    var radiusValues = {
        "1": "100m",
        "2": "200m",
        "3": "300m",
        "4": "400m",
        "5": "500m"
    }

    $(function () {
        $('#rangeText').text(rangeValues[$('#rangeInput').val()]);

        $('#rangeInput').on('input change', function () {
            $('#rangeText').text(rangeValues[$(this).val()]);
        });
    });
    
    $(function () {

        $('#radiusText').text(radiusValues[$('#radiusInput').val()]);

        $('#radiusInput').on('input change', function () {
            $('#radiusText').text(radiusValues[$(this).val()]);
        });
    });
</script>

app/views/schools/_crimesmap.html.erb
<div id="map"></div>
<script type="text/javascript"> 
    (function initMap() {
        document.getElementById('map').style.height = String(document.getElementsByClassName('container fill')[0].offsetHeight) + "px";
        
        var centerPos = {lat: <%= school.latitude %>, lng: <%= school.longitude %>}
        var zoom_level = 17;
        
        map = new google.maps.Map(document.getElementById('map'), {
              zoom: zoom_level,
              center: centerPos
        });
        
        var marker = new google.maps.Marker({
          position: centerPos,
          map: map
        });
        
        <% crimes.each do |c| %>
            var pos = {lat: <%= c.shape.coordinates[1] %>, lng: <%= c.shape.coordinates[0] %>};
            var marker = new google.maps.Marker({
              position: pos,
              map: map,
              icon: "https://maps.google.com/mapfiles/ms/icons/blue-dot.png"
            });
        <% end %>
        
        var gmInput = document.getElementById('map-input');
        var searchBox = new google.maps.places.SearchBox(gmInput);
        
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });
        
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();
          if (places.length == 0) {
            return;
          }
          var pl = places[0];
          var pl_coords = pl.geometry.location;
          
          var bounds = map.getBounds();
          var ne = bounds.getNorthEast(); // LatLng of the north-east corner
          var sw = bounds.getSouthWest(); // LatLng of the south-west corner
          var zoomlevel = 17;
          var pre = "0", elem = "0", mid = "0", high = "0";
          if(document.getElementById('static_pages_pre').checked)
            pre = "1";
          if(document.getElementById('static_pages_elem').checked)
            elem = "1";
          if(document.getElementById('static_pages_mid').checked)
            mid = "1";
          if(document.getElementById('static_pages_high').checked)
            high = "1";
          $.ajax({
            type: "POST",
            url: '/filter',
            data: {chkbox_state: {'pre': pre, 'elem': elem, 'mid': mid, 'high': high}, bounds: {lat_max: ne.lat(), lat_min: sw.lat(), lng_min: sw.lng(), lng_max: ne.lng(), center_lat: pl_coords.lat(), center_lng: pl_coords.lng(), zoom_level: zoomlevel}}
          });
        });
    })();
</script>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>
      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_rating.html.erb
<% 5.times do |i| %>
    <% if i < @score %>
        <div class="glyphicon glyphicon-star"></div>
    <% else %>
        <div class="glyphicon glyphicon-star-empty"></div>
    <% end %>
<% end %>

app/views/schools/_reviewslist.html.erb
<% reviews = Review.where(:school_id => id.to_i) %>
<% if reviews.length == 0 then %>
    <div class="alert alert-danger" style="margin-top: 20%; text-align: center">
      There are no reviews for this school yet!
    </div>
<% else %>
    <h3>List of Reviews: </h3>
    <ul class="list-group">
    <% reviews.find_each do |r| %>
       <li class="list-group-item">
          <%= r["title"] %>  | 
          <%= r["comment"] %>
        </li>
    <% end %>
    </ul>
<% end %>

app/views/schools/_show.html.erb
<%= link_to "Back", root_path %>

<p id="notice"><%= notice %></p>

<div class="page-header" style="margin-top: -5%">
    <h1><%= school.name %></h1>
    <h3><%= school.grade_level %></h2>
    <h3>Safety Rating: 
        <div id="safety-rating"></div>
    </h3>
</div>

<div id="school-page-body">
    <div class="review-button" style= "text-align: center; margin-top: 5%">
        <% if logged_in? %>
            <%= link_to "Post a Review", new_school_review_path(school), class: "btn btn-primary", :remote => true %>
        <% end %>
    </div>
    <div class="favorite-button" style= "text-align: center; margin-top: 5%">
        <% if logged_in? %>
            <% if favorite? school %>
                <%= link_to "Remove Bookmark", favorite_school_path(school, type: "unfavorite"), class: "btn btn-primary",
                    method: :post %>
            <% else %>
                <%= link_to "Bookmark", favorite_school_path(school, type: "favorite"), class: "btn btn-primary",
                    method: :post %>
            <% end %>
        <% end %>
    </div>
    
    <div id="crimes_filter" style="border-bottom: 1px solid #ccc;">
        <%= render partial: 'crimesfilter', locals: {id: school.id} %>
    </div>
    
    <div id="crimes-list">
      <%= render partial: 'crimes', locals: {crimes: @crimes} %>
    </div>
    
    <div id="reviews-list">
        <%= render partial: 'reviewslist', locals: {id: school.id} %>
    </div>

</div>

app/views/schools/crimefilter.js.erb
$("#map_part").html("<%= escape_javascript(render partial: 'crimesmap', locals: { school: @school, crimes: @crimes }) %>");
$("#crimes-list").html("<%= escape_javascript(render partial: 'crimes', locals: { crimes: @crimes }) %>");
$("#safety-rating").html("<%= escape_javascript(render partial: 'rating', locals: {score: @score}) %>");

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.js.erb
$("#list").html("<%= escape_javascript(render partial: 'show', locals: { school: @school, crimes: @crimes }) %>");
$("#map_part").html("<%= escape_javascript(render partial: 'crimesmap', locals: { school: @school, crimes: @crimes }) %>");
$("#safety-rating").html("<%= escape_javascript(render partial: 'rating', locals: {score: @score}) %>");

app/views/schools/submit.js.erb
$("#list").html("<%= escape_javascript(render partial: 'show', locals: { school: @school, crimes: @crimes }) %>");
$("#map_part").html("<%= escape_javascript(render partial: 'crimesmap', locals: { school: @school, crimes: @crimes }) %>");
$("#safety-rating").html("<%= escape_javascript(render partial: 'rating', locals: {score: @score}) %>");