config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                    Controller#Action
#               root GET    /                                              static_pages#home
#             filter POST   /filter(.:format)                              static_pages#filter
#          mapchange POST   /mapchange(.:format)                           static_pages#mapchange
#        crimefilter POST   /crimefilter(.:format)                         schools#crimefilter
#              about GET    /about(.:format)                               static_pages#about
#            contact GET    /contact(.:format)                             static_pages#contact
#             signup GET    /signup(.:format)                              users#new
#                    POST   /signup(.:format)                              users#create
#       sessions_new GET    /sessions/new(.:format)                        sessions#new
#              login GET    /login(.:format)                               sessions#new
#                    POST   /login(.:format)                               sessions#create
#             logout DELETE /logout(.:format)                              sessions#destroy
#     school_reviews GET    /schools/:school_id/reviews(.:format)          reviews#index
#                    POST   /schools/:school_id/reviews(.:format)          reviews#create
#  new_school_review GET    /schools/:school_id/reviews/new(.:format)      reviews#new
# edit_school_review GET    /schools/:school_id/reviews/:id/edit(.:format) reviews#edit
#      school_review GET    /schools/:school_id/reviews/:id(.:format)      reviews#show
#                    PATCH  /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    PUT    /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    DELETE /schools/:school_id/reviews/:id(.:format)      reviews#destroy
#    favorite_school POST   /schools/:id/favorite(.:format)                schools#favorite
#            schools GET    /schools(.:format)                             schools#index
#             school GET    /schools/:id(.:format)                         schools#show
#            reviews GET    /reviews(.:format)                             reviews#index
#                    POST   /reviews(.:format)                             reviews#create
#         new_review GET    /reviews/new(.:format)                         reviews#new
#        edit_review GET    /reviews/:id/edit(.:format)                    reviews#edit
#             review GET    /reviews/:id(.:format)                         reviews#show
#                    PATCH  /reviews/:id(.:format)                         reviews#update
#                    PUT    /reviews/:id(.:format)                         reviews#update
#                    DELETE /reviews/:id(.:format)                         reviews#destroy
#              users GET    /users(.:format)                               users#index
#                    POST   /users(.:format)                               users#create
#           new_user GET    /users/new(.:format)                           users#new
#          edit_user GET    /users/:id/edit(.:format)                      users#edit
#               user GET    /users/:id(.:format)                           users#show
#                    PATCH  /users/:id(.:format)                           users#update
#                    PUT    /users/:id(.:format)                           users#update
#                    DELETE /users/:id(.:format)                           users#destroy
#

Rails.application.routes.draw do
  get '/', to: 'static_pages#home', :as => 'root'
  post 'filter', to: 'static_pages#filter'
  post 'mapchange', to: 'static_pages#mapchange'
  post 'crimefilter', to: 'schools#crimefilter'
  post 'submit', to: 'schools#submit'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'sessions/new'
  get 'login',   to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  resources :schools, only: [:index, :show] do
    resources :reviews
    member do
      post 'favorite'
    end
  end
  resources :reviews
  resources :users, except: :index
   
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # skip_before_filter :verify_authenticity_token, :only => [:new]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    respond_to do |format|
        format.js
    end
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    # @review = Review.new(review_params)
    @review = current_user.reviews.build(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :rating, :comment, :school_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<h3>New Review</h3>

<%= form_for(@review, url: submit_path, :method => 'post', :remote => true) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="review_field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="review_field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="review_field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="review_field" style="visibility:hidden">
    <%= f.label :school_id %><br>
    <%= f.number_field :school_id, :value => params[:school_id]%>
  </div>
  <div class="review_actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.js.erb
$("#school-page-body").html("<%= escape_javascript(render partial: 'form') %>")

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<p id="notice"><%= notice %></p>
<div class = review_page>
  <h3>Review of <%= School.find(Review.find(params[:id]).school_id).name %></h3>
  <% @user = User.find(Review.find(params[:id]).user_id) %>
  <h4>Submitted by <%= link_to @user.name, user_path(@user.id) %></h4>
  <h5><%= Review.find(params[:id]).title %></h3>
  <p><%= Review.find(params[:id]).rating %></sp>
  <p><%= Review.find(params[:id]).comment %></p>
</div>

<div class="edit_and_back">
<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>
</div>