config/routes.rb
# == Route Map
#
#             Prefix Verb   URI Pattern                                    Controller#Action
#               root GET    /                                              static_pages#home
#             filter POST   /filter(.:format)                              static_pages#filter
#          mapchange POST   /mapchange(.:format)                           static_pages#mapchange
#        crimefilter POST   /crimefilter(.:format)                         schools#crimefilter
#              about GET    /about(.:format)                               static_pages#about
#            contact GET    /contact(.:format)                             static_pages#contact
#             signup GET    /signup(.:format)                              users#new
#                    POST   /signup(.:format)                              users#create
#       sessions_new GET    /sessions/new(.:format)                        sessions#new
#              login GET    /login(.:format)                               sessions#new
#                    POST   /login(.:format)                               sessions#create
#             logout DELETE /logout(.:format)                              sessions#destroy
#     school_reviews GET    /schools/:school_id/reviews(.:format)          reviews#index
#                    POST   /schools/:school_id/reviews(.:format)          reviews#create
#  new_school_review GET    /schools/:school_id/reviews/new(.:format)      reviews#new
# edit_school_review GET    /schools/:school_id/reviews/:id/edit(.:format) reviews#edit
#      school_review GET    /schools/:school_id/reviews/:id(.:format)      reviews#show
#                    PATCH  /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    PUT    /schools/:school_id/reviews/:id(.:format)      reviews#update
#                    DELETE /schools/:school_id/reviews/:id(.:format)      reviews#destroy
#    favorite_school POST   /schools/:id/favorite(.:format)                schools#favorite
#            schools GET    /schools(.:format)                             schools#index
#             school GET    /schools/:id(.:format)                         schools#show
#            reviews GET    /reviews(.:format)                             reviews#index
#                    POST   /reviews(.:format)                             reviews#create
#         new_review GET    /reviews/new(.:format)                         reviews#new
#        edit_review GET    /reviews/:id/edit(.:format)                    reviews#edit
#             review GET    /reviews/:id(.:format)                         reviews#show
#                    PATCH  /reviews/:id(.:format)                         reviews#update
#                    PUT    /reviews/:id(.:format)                         reviews#update
#                    DELETE /reviews/:id(.:format)                         reviews#destroy
#              users GET    /users(.:format)                               users#index
#                    POST   /users(.:format)                               users#create
#           new_user GET    /users/new(.:format)                           users#new
#          edit_user GET    /users/:id/edit(.:format)                      users#edit
#               user GET    /users/:id(.:format)                           users#show
#                    PATCH  /users/:id(.:format)                           users#update
#                    PUT    /users/:id(.:format)                           users#update
#                    DELETE /users/:id(.:format)                           users#destroy
#

Rails.application.routes.draw do
  get '/', to: 'static_pages#home', :as => 'root'
  post 'filter', to: 'static_pages#filter'
  post 'mapchange', to: 'static_pages#mapchange'
  post 'crimefilter', to: 'schools#crimefilter'
  post 'submit', to: 'schools#submit'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'sessions/new'
  get 'login',   to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  resources :schools, only: [:index, :show] do
    resources :reviews
    member do
      post 'favorite'
    end
  end
  resources :reviews
  resources :users, except: :index
   
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "schoolsafe", root_path, id: "logo" %>
    <div class="col-sm-3 col-md-3">
      <div class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" id="map-input" style="width: 600px">
        </div>
      </div>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="padding-right: 10px">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact",   contact_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCT0DTbOr1pJzEwQqtrY-pIR69-NZVnwtI &libraries=places">
    </script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container fill">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  
</html>